# Generated by Django 2.1.1 on 2018-09-19 16:29

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info1', models.CharField(default='', max_length=50, verbose_name='信息1')),
                ('text_info2', models.CharField(default='', max_length=50, verbose_name='信息2')),
                ('text_info3', models.CharField(default='', max_length=50, verbose_name='信息3')),
                ('cover', models.ImageField(default=None, upload_to='static/assets/images/banner', verbose_name='轮播图')),
                ('link_url', models.URLField(max_length=100, verbose_name='图片链接')),
                ('idx', models.IntegerField(verbose_name='索引')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布日期')),
                ('cover', models.ImageField(upload_to='static/assets/images/blog', verbose_name='博客封面')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数')),
                ('recommend', models.BooleanField(default=False, verbose_name='推荐博客')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('infor', models.TextField(max_length=500, verbose_name='简介')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='发布时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('blog', models.ForeignKey(on_delete=True, to='myapp.Blog', verbose_name='博客')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', models.TextField(max_length=200, verbose_name='课程简介')),
                ('cover', models.ImageField(default=None, upload_to='static/assets/images/courses', verbose_name='课程封面')),
                ('runtime', models.IntegerField(default=0, verbose_name='时长')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('attachment', models.FileField(blank=True, upload_to='', verbose_name='课程资料包')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('learn_num', models.IntegerField(default=100, verbose_name='学习人数')),
                ('comment_num', models.IntegerField(default=987, verbose_name='评论数')),
                ('level', models.CharField(choices=[('初级', '初级'), ('中级', '中级'), ('高级', '高级')], default='初级', max_length=20, verbose_name='等级')),
                ('star', models.IntegerField(default=5, verbose_name='星级')),
                ('price', models.IntegerField(default=100, verbose_name='价格')),
                ('recommend', models.BooleanField(default=True, verbose_name='是否推荐')),
                ('published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('category', models.ForeignKey(on_delete=True, to='myapp.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('cover', models.ImageField(default=None, upload_to='static/assets/images/org', verbose_name='博客封面')),
            ],
            options={
                'verbose_name': '合作机构',
                'verbose_name_plural': '合作机构',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('course', models.ForeignKey(on_delete=True, to='myapp.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='StarStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('company', models.CharField(max_length=50, verbose_name='公司')),
                ('head_img', models.ImageField(upload_to='static/assets/images/students', verbose_name='头像')),
                ('comment', models.CharField(max_length=50, verbose_name='评论')),
            ],
            options={
                'verbose_name': '明星学员',
                'verbose_name_plural': '明星学员',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('face', models.ImageField(upload_to='static/assets/images/teacher', verbose_name='头像')),
                ('title', models.CharField(max_length=20, verbose_name='头衔')),
                ('infor', models.TextField(blank=True, max_length=300, verbose_name='简介')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('video', models.FileField(upload_to='static/video', verbose_name='视频文件')),
                ('play_time', models.CharField(max_length=20, verbose_name='播放时长')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('course', models.ForeignKey(on_delete=True, to='myapp.Course', verbose_name='课程')),
                ('section', models.ForeignKey(on_delete=True, to='myapp.Section', verbose_name='章节')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=True, to='myapp.Teacher', verbose_name='讲师'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=None, on_delete=True, to='myapp.BlogCategory', verbose_name='博客分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='myapp.Tags', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
